sources:
  - name: earthquake_api
    database: earthquake_project
    schema: raw
    tables:
      - name: Earthquake
  - name: amazon_s3
    database: earthquake_project
    schema: amazon_s3
    tables:
      - name: allCountries
      - name: countries_regional_codes
