sources:
  - name: earthquake
    database: earthquake_project
    schema: raw
    tables:
      - name: earthquake
  - name: all_countries_geocode
    database: earthquake_project
    schema: amazon_s3
    tables:
      - name: allcountries
