FROM python:3.11-slim

ENV PYTHONPATH=/app/orchestration \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Install system deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
  && rm -rf /var/lib/apt/lists/*


COPY . /app

# Install Python requirements (adjust if you use pyproject instead)
RUN pip install --no-cache-dir -r requirements.txt

# install dbt packages at build time
WORKDIR /app/transform/dbt/earthquake
RUN dbt deps

# Dagster gRPC port
EXPOSE 4000

# Start Dagster user-code gRPC server (adjust module path if needed)
WORKDIR /app
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-d", "/app/orchestration", "-f", "/app/orchestration/orchestration/definitions.py"]
