earthquake:
  target: dev
  outputs:
    lint:
      type: duckdb
      path: ":memory:"
      schema: main
      threads: 4

    dev:
      type: snowflake
      account: '{{ env_var("SNOWFLAKE_ACCOUNT_ID") }}'

      # User/password auth
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: '{{ env_var("SNOWFLAKE_ROLE") }}'
      database: EARTHQUAKE_PROJECT_DEV
      warehouse: '{{ env_var("SNOWFLAKE_WAREHOUSE") }}'
      schema: earthquake_dev
      threads: 1

    prod:
      type: snowflake
      account: '{{ env_var("SNOWFLAKE_ACCOUNT_ID") }}'

      # User/password auth
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: '{{ env_var("SNOWFLAKE_ROLE") }}'
      database: '{{ env_var("SNOWFLAKE_DATABASE") }}'
      warehouse: '{{ env_var("SNOWFLAKE_WAREHOUSE") }}'
      schema: earthquake_prod
      threads: 1

    sqlfluff_linter: #dummy profile for github action linter
      type: snowflake
      account: dummy
      user: dummy
      password: dummy

      role: dummy
      database: dummy
      warehouse: dummy
      schema: dummy
      threads: 1
